# Generated by Django 5.2.3 on 2025-07-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_customuser_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='products',
            field=models.JSONField(default=dict),
        ),
    ]
