# Generated by Django 5.2.3 on 2025-07-03 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_customuser_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Номер должен быть в формате: '+7XXXXXXXXXX'.", regex='^\\+7\\d{10}$')], verbose_name='Телефон'),
        ),
    ]
